# CircleCI configuration file
version: 2
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    working_directory: ~/fathomteam/moab
    parallelism: 1
    shell: /bin/bash --login
    # To see the list of pre-built images that CircleCI provides for most common languages see
    # https://circleci.com/docs/2.0/circleci-images/
    docker:
    - image: cimg/base:2021.07
    steps:
    # Machine Setup
    #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
    # The following `checkout` command checks out your code to your working directory. 
    - checkout
    # Dependencies
    #   This would typically go in either a build or a build-and-test job when using workflows
    # Run the setup and install any pre-dependencies for building MOAB 
    - run: |
        sudo apt -yy update
        sudo apt -yy install libhdf5-mpi-dev libnetcdf-mpi-dev libmetis-dev libopenblas-dev
        autoreconf -fi
    # Run the actual configuration command
    - run: |
        ./configure --with-hdf5=/usr/include/hdf5/openmpi --with-netcdf=/usr/lib/x86_64-linux-gnu/netcdf/mpi --with-metis=/usr LDFLAGS="-L/usr/lib/x86_64-linux-gnu/hdf5/openmpi/ -L/usr/lib/x86_64-linux-gnu/openblas-serial" --with-mpi=/usr/lib/x86_64-linux-gnu/openmpi CC=mpicc CXX=mpicxx FC=mpif90 F77=mpif77
        make all -j4
        make check -j4
  dockerbuild:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: vijaysm/moab-root 
          path: ./docker/TempestRemap 
          tag: moabtr 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  docker_build:
    jobs:
      - dockerbuild
